version: '3.1'
services:
  ewm-client:
    build: ewm-client
    image: amazoncorretto:11-alpine-jdk
    container_name: ewm-client
    environment:
      - EXPLORE-WITH-ME-SERVICE_URL=http://service:9091/explore-with-me-service

    ports:
      - "8080:8080"


  ewm-service:
    build: ewm-service
    image: amazoncorretto:11-alpine-jdk
    container_name: ewm-service
    environment:
      - EXPLORE-WITH-ME-STATISTICS_URL=http://stats:9090
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - ewm-client
    ports:
      - "9091:9091"

  ewm-db:
    image: postgres:14-alpine

  stats_db:
    image: postgres:14-alpine

  stats-server:
    build: stats-server
    image: amazoncorretto:11-alpine-jdk
    container_name: stats-server
    environment:
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - ewm-client
    ports:
      - "9090:9090"
