version: '3.1'
services:

  stats-server:
    build: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmuser

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmuser

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmuser
      - stat-server.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6547:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmuser
